### ISSUE TITLE
Required php extension "imagettftext" does not exist

### ISSUE THREAD

**Issue by benediktcarda** [ayeo/gs1_128#10] opened 2020-02-25 06:08 UTC
In my opinion the composer requirement for extensions "ext-imagettftext" is not satisfiable because there is no such an extension:
https://www.php.net/manual/de/extensions.alphabetical.php

This requirement should be deleted. The function imagettftext() is provided by GD when freetype support is enabled. I have this function available in my php installation but still composer denies to install ayeo/gs1_128 due to non-existence of ext-imagettftext.

**Comment by ayeo** [comment] 2020-02-25 11:47
Thank you for reporting this. It seems you are right. Probably it should be "ext-gd". I will look closer at this later.

**Comment by ayeo** [comment] 2020-02-26 14:40
I have just pushed fixes, composer package is also updated. The problem is that library requires both GD and Free Type extensions installed. But it is not possible to check Free Type at the build/composer level. In case of lack of Free Type you get RuntimeException while trying to print barcode.

**Comment by ayeo** [comment] 2020-02-26 14:40
Let me know if it work fine to you ;)

**Closed as completed** 2020-03-03 20:11 UTC
